name: Deploy to heroku

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.13 # This is the action
        with:
          heroku_api_key: 7920548f-e14f-4f26-bd9c-a7b6bee0b497
          heroku_app_name: "team-2" #Must be unique in Heroku
          heroku_email: "ecomje@gmail.com"
          appdir: "backend"
          env_file: ".env.prod"